routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','HomeController@homepage')->name('homepage');

/*
Route::get('/usercontroller/path',[
    'middleware' => 'first',
    'uses' => 'UserController@showPath'
]);
*/
/*
Route::get('/deposit/{amount}','TestController@deposit');
Route::get('/withdraw/{amount}','TestController@withdraw');
Route::get('/blockchain','TestController@index');
Route::get('/reinvest','TestController@reinvest');
Route::get('auto_withdraw','TestController@auto_withdraw');
*/

/**
 * Facebook provider url
 */
Route::get('facebook/login','Auth\LoginController@redirectToProvider')->name('facebook');
Route::get('facebook/login/callback','Auth\LoginController@handleProviderCallback');

/**
 * Auth and email confirmation route with homepage
 */

Route::get('test_home',  function (){
    return view('pages.home');
})->name('test_home');
Route::get('test_about', function (){
    return view('pages.about');
});
Route::get('get_started', function (){
    return view('pages.get_started');
});
Route::get('terms', function (){
    return view('pages.terms');
});
Route::get('contact_us', function (){
    return view('pages.contact');
});


Auth::routes();
Route::get('confirm/{token}','Auth\RegisterController@confirm');
Route::get('/home', 'HomeController@index')->name('home');

Route::get('/ref/{name}','Auth\RegisterController@referral')->where('name','[0-9a-zA-Z_-]+');
/**
 * User dashboard routes ::Frontend
*/
Route::get('/member/createusername','Auth\LoginController@create_username')->name('create_username');
Route::post('/member/createusername','Auth\LoginController@create_username_post')->name('create_username_post');

Route::get('/member/deposit','TransactionController@deposit')->name('deposit');
Route::post('/member/deposit','TransactionController@deposit_post')->name('deposit_post');
Route::get('/member/withdraw','TransactionController@withdraw')->name('withdraw');
Route::post('/member/withdraw','TransactionController@withdraw_post')->name('withdraw_post');
Route::get('/member/reinvest','TransactionController@reinvest')->name('reinvest');
Route::post('/member/reinvest','TransactionController@reinvest_post')->name('reinvest_post');
Route::get('/member/withdrawdeposit','TransactionController@withdraw_deposit')->name('withdrawdeposit');
Route::post('/member/canceldeposit','TransactionController@withdraw_deposit_post')->name('cancel_deposit');
Route::get('/member/history','UserController@finance_history')->name('history');
Route::get('/member/automate','UserController@automation')->name('automation');
Route::post('/member/automate','UserController@automation_post')->name('automation_post');
Route::get('/member/affiliate','AffiliateController@index')->name('affiliate');
Route::post('/member/affiliate_post','AffiliateController@affiliate_post')->name('affiliate_post');
Route::resource('/member/setting','SettingsController');;//->name('ph.create');
Route::get('/member/leaderboard','HomeController@leaderboard')->name('leaderboard');
/**
 * Guest routes
 */
Route::post('/gateway','BitcoinController@ajax_check');

Route::get('/about','HomeController@faq')->name('about');
Route::get('/privacy_policy','HomeController@privacy_policy')->name('privacy_policy');
//Route::get('/terms_of_service','HomeController@terms_of_service')->name('tos');
Route::get('/member/contact','HomeController@contact_us')->name('contactus');

Route::post('/member/contact','HomeController@contact_process')->name('contact_post');

Route::get('/member/resend','Auth\RegisterController@resend')->name('resend');

Route::group(['namespace'=>'Admin','middleware'=>'admin','prefix' =>'admin'],function(){
    Route::get('index','AdminController@index')->name('admin_index');
    Route::get('viewwithdraw','AdminController@withdraw_request')->name('withdraw_request');
    Route::get('makepayment','AdminController@make_payment')->name('run_withdraw');
    Route::post('makepayment','AdminController@make_payment_post')->name('make_payment');
    Route::post('makesinglepayment','AdminController@make_single_payment_post')->name('make_single_payment');
    Route::post('cancelsinglepayment','AdminController@cancel_payment_post')->name('cancel_payment');
    Route::get('leaderboard','AdminController@view_leaderboard')->name('view_board');
    Route::get('view_users','AdminController@view_users')->name('view_user');

    Route::get('wallet_info','AdminController@wallet_info')->name('wallet_info');
    Route::get('addressbalance','AdminController@address_balance')->name('address_balance');
    Route::post('addressbalance','AdminController@address_balance_post')->name('address_balance_post');
    Route::get('wallet_setting','SuperAdminController@wallet_setting')->name('wallet_setting');
    Route::post('wallet_setting','SuperAdminController@wallet_setting_post')->name('wallet_setting_post');
    Route::get('add','SuperAdminController@add_admin')->name('add_admin');
    Route::post('add','SuperAdminController@add_admin_post')->name('add_admin_post');
    Route::get('view','SuperAdminController@view_admin')->name('view_admin');
    Route::post('removeadmin','SuperAdminController@remove_admin')->name('remove_admin');
    Route::get('deletedadmins','SuperAdminController@deleted_admin')->name('deleted_admin');
    Route::post('restoreadmin','SuperAdminController@restore_admin')->name('restore_admin');
    Route::post('removeuser','SuperAdminController@remove_user')->name('remove_user');
    Route::get('deletedusers','SuperAdminController@deleted_user')->name('deleted_user');
    Route::post('restoreuser','SuperAdminController@restore_user')->name('restore_user');
    Route::post('changesetting','AdminController@change_admin_passcode_post')->name('changepasscode');
    Route::get('changesettings','AdminController@change_admin_passcode')->name('changepasscodeview');

    Route::get('add_user','AdminController@create_user')->name('create_user');
    Route::post('add_user_post','AdminController@create_user_post')->name('create_user_post');
    Route::get('viewfalseusers','AdminController@get_users')->name('view_false_users');

    Route::post('view_trans','AdminController@view_trans')->name('view_trans');
    Route::post('update_trans','AdminController@update_trans')->name('update_trans');
    Route::post('update_trans_post','AdminController@update_trans_post')->name('update_trans_post');

    Route::post('add_trans','AdminController@add_trans')->name('add_trans');
    Route::post('add_trans_posts','AdminController@add_trans_post')->name('add_trans_post');

    Route::post('update_user','AdminController@update_user')->name('user_update');
    Route::post('update_user_post','AdminController@update_user_post')->name('user_update_post');

    Route::get('sendmail','AdminController@send_one_mail')->name('sendone');
    Route::post('sendmailpost','AdminController@send_one_mail_post')->name('sendonepost');

    Route::get('sendmany','AdminController@send_many_mail')->name('sendmany');
    Route::post('sendmanypost','AdminController@send_many_post')->name('sendmanypost');
});

resources/views/front/affiliateprogram.blade.php
@extends('layouts.template')

@section('content')
    <div class="content-wrapper">
        <section class="content-header">
            <h1>
                AFFILIATE
                <small>EARN MORE THROUGH AFFILIATES</small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="{{ route('home') }}"><i class="fa fa-dashboard"></i> Home</a></li>
                <li class="active">Affiliate</li>
            </ol>
        </section>
        @include('partials.errorbag')
        @if(session()->has('info'))
            @include('partials.error',['type'=>session('info')['type'],'message'=> session('info')['message']])
        @endif
        <section class="content">
            <div class="form-group">
                <label>Your affiliate link</label>
                <input class="form-control" type="text" readonly value="{{ url('ref/'. auth()->user()->name)  }}"/>
            </div>
            <div class="box">
                <div class="box-header with-border">

                </div>
                <div class="box-body">
                    <div class="table-responsive">
                        <table class="table table-hover">
                            <thead>
                            <tr>
                                <th>Username</th>
                                <th>Real Deposit</th>
                                <th>Commission</th>
                                <th>Member BTC address</th>
                                <th>Registered</th>
                                <th>Last login </th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($affiliate as $dd)
                                <tr>
                                    <td>{{ \App\User::find($dd->child_id)->name }}</td>
                                    <td><span class="label label-success">{{ sprintf('%.8f',$dd->real_deposit) }}<i class="fa fa-btc"></i></span></td>
                                    <td><span class="label label-danger" data-content="{{$dd->commission}}" id="commission{{$dd->child_id}}">{{ sprintf('%.8f',$dd->commission) }}<i class="fa fa-btc"></i></span></td>
                                    <td><a class="btn btn-default">{{ $dd->member_btc_address }}</a></td>
                                    <td>{{ $dd->member_registered }}</td>
                                    <td>{{ $dd->member_last_login }}</td>
                                    <td>
                                        @if(!$dd->reinvested)

                                            @component('partials.action')
                                            {{ $dd->child_id }}
                                            @endcomponent

                                        @endif
                                    </td>
                                </tr>
                            @endforeach
                        </table>
                    </div>
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    {{ $affiliate->links() }}
                </div>
                <!-- /.box-footer-->
            </div>
        </section>
    </div>
@endsection

resources/views/front/automation.blade.php
@extends('layouts.template')
@push('styles')
<link href="https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css" rel="stylesheet">
@endpush
@push('scripts')
<script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"></script>
@endpush


@section('content')
    <div class="content-wrapper">
        <section class="content-header">
            <h1>
                AUTOMATION
                <small>AUTOMATE YOUR EARNINGS</small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="{{ route('home') }}"><i class="fa fa-dashboard"></i> Home</a></li>
                <li class="active">Automation</li>
            </ol>
        </section>
        @include('partials.errorbag')
        @if(session()->has('info'))
            @include('partials.error',['type'=>session('info')['type'],'message'=> session('info')['message']])
        @endif
        <section class="content">
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">Automate to step up your earning</h3>
                </div>
                <div class="box-body">
                    <form method="post" action="{{ route('automation_post') }}">
                        {{ csrf_field() }}
                    <div class="row">
                        <div class="col-md-6">
                            <div class="callout callout-success text-center">
                                <strong>Automate Withdrawal</strong>
                            </div>
                            <div class="row text-center"><strong>Enable Auto withdrawal</strong><small>
                                    (once every 24 hours)
                                </small></div>
                            <div class="row text-center">
                                <input data-toggle="toggle" {{ $auto_with ? 'checked':''}}  data-on="<i class='fa fa-check'></i> Enabled"
                                       data-off="<i class='fa fa-close'></i> Disabled" name="auto_with_check" type="checkbox"/>
                            </div>

                                <div class="form-group">
                                    <label for="member_auto_withdraw_address">Enter your BTC address</label>
                                    <div class="input-group">
                                        <span class="input-group-addon"><i class="fa fa-paper-plane-o"></i></span>
                                        <input class="form-control" name="auto_withdraw_address"
                                               placeholder="Where Bitcoins should be sent (eg. 1Feabc1QaKQutScm39hexYUuqFz89IAy9)"
                                               value="{{ old('auto_withdraw_address') }}" type="text">
                                    </div>
                                    <small id="bitcoinaddressHelp" class="form-text text-muted">
                                        We are completely transparent, and you can track all deposits on our site
                                        <a href="https://blockchain.info/address/">here</a></small>
                                </div>

                        </div>
                        <div class="col-md-6">
                            <div class="callout callout-success text-center">
                                <strong>Automate Reinvest</strong>
                            </div>
                            <div class="row text-center"><strong>Enable Automatic reinvestment</strong><small>
                                    (instantly)
                                </small></div>
                            <div class="row text-center">
                                <input data-toggle="toggle" {{ $auto_invest ? 'checked':''  }} name="auto_reinvest_check"
                                       data-on="<i class='fa fa-check'></i> Enabled" data-off="<i class='fa fa-close'></i> Disabled" type="checkbox"/>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-offset-4 col-md-4 col-sm-offset-4 col-sm-4">
                            <br/>
                            <button type="submit" class="btn btn-primary btn-block">Save Changes</button>
                        </div>
                    </div>
                    </form>
                </div>
            </div>
        </section>
    </div>
@endsection

resources/views/front/contact.blade.php
@extends('layouts.template')


@section('content')
    <div class="content-wrapper">
        <section class="content-header">
            <h1>
                CONTACT US
                <small>SEND US A MESSAGE</small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="{{ route('home') }}"><i class="fa fa-dashboard"></i> Home</a></li>
                <li class="active">Contact</li>
            </ol>
        </section>
        @include('partials.errorbag')
        @if(session()->has('info'))
            @include('partials.error',['type'=>session('info')['type'],'message'=> session('info')['message']])
        @endif
        <section class="content">
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">You can contant us anytime</h3>
                </div>
                <div class="box-body">
                    <div class="col-md-offset-4 col-md-4">
                    <form role="form" method="POST" action="{{ route('contact_post') }}">
                        {{ csrf_field() }}
                        <div class="box-body">
                            <div class="form-group">
                                <label for="exampleInputEmail1">Name</label>
                                <input class="form-control" name="username" value="{{old('username')}}" placeholder="Enter name" type="text">
                            </div>
                            <div class="form-group">
                                <label for="exampleInputPassword1">Email address</label>
                                <input class="form-control" name="email" value="{{old('email')}}" id="exampleInputPassword1" placeholder="Enter email" type="email">
                            </div>

                            <div class="form-group">
                                <label for="exampleInputPassword1">Message</label>
                                <textarea class="form-control" name="message" cols="3" rows="8">{{old('message')}}</textarea>
                            </div>
                        </div>
                        <!-- /.box-body -->

                        <div class="box-footer">
                            <button type="submit" class="btn btn-primary btn-block">Send</button>
                        </div>
                    </form>
                        </div>
                </div>
                <!-- /.box-body -->
                <div class="box-footer">

                </div>
                <!-- /.box-footer-->
            </div>
        </section>

    </div>
 @endsection

resources/views/front/deposit.blade.php
@extends('layouts.template')

@section('content')
    <div class="content-wrapper">
        <section class="content-header">
            <h1>
                DEPOSIT
                <small>START EARNING BITCOIN</small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="{{ route('home') }}"><i class="fa fa-dashboard"></i> Home</a></li>
                <li class="active">Deposit</li>
            </ol>
        </section>
        @include('partials.errorbag')
        @if(session()->has('info'))
            @include('partials.error',['type'=>session('info')['type'],'message'=> session('info')['message']])
        @endif

        <section class="content">
            <div class="box">
                <div class="panel-body">
                    To start earning Bitcoins, pay in any number of bitcoins above {{ env('MIN_DEPOSIT') }} <i class="fa fa-btc"></i> to your personal Bitcoin address below.<br>
                    Your payment has to go through a validation process to be credited. This process usually takes up to 60 minutes, depending on the speed of Bitcoin service. Sometimes, you can face delays for up to 24 hours, contact us if you experience any difficulties.<br>
                    <br>
                    After successful validation of your payment, click on the button below and your deposit balance will be automatically credited, and you will get your hourly income <strong>{{ env('HOURLY_GROWTH_RATE')*100 }}% (about {{ env('DAILY_GROWTH_RATE')*100 }}% daily) lifetime!</strong> <br>
                    <!--For instance, if you deposit 1 <i class="fa fa-btc"></i>, you will get 3 <i class="fa fa-btc"></i> after 30 days! We are completely transparent, you can check site income whenever you want just by checking our main wallet <a href="https://blockchain.info/address/">here</a>.<br>-->
                    <br>
                    <strong>Notice:</strong> For earnings calculations, we round up and assume that {{ env('DAILY_GROWTH_RATE')*100 }}% divided by 24 hours is <strong>{{ env('HOURLY_GROWTH_RATE')*100 }}% per 1 hour</strong>, because of round-off error your earnings can be slightly different from {{ env('DAILY_GROWTH_RATE')*100 }}%/daily <strong>(</strong> in most cases you will earn a little bit more<strong>)</strong><br>
                    <hr>
                    <strong style="color: lightgreen;">Notice 2:</strong> Because of high interest of our site the system checks for new deposits ONLY if you click at
                    <b>'CONFIRM DEPOSIT'</b> after your bitcoin transaction has gotten 3 confirmations<br>
                    <hr>
                    <br>
                    You can request withdraw whenever you want, even just after first valorisation (every hour)<br>
                    <hr>
                    <div class="form-group">
                        <label for="bitcoinaddress">Your personal Bitcoin address</label>
                        <div class="input-group">
                            <span class="input-group-addon"><i class="fa fa-money"></i></span>
                            <input class="form-control" id="bitcoinaddress" value="{{ $deposit_address }}" readonly type="text">
                        </div>
                        <small id="bitcoinaddressHelp" class="form-text text-muted">After 3 confirmations click on the button below and your deposit will be automatically credited to your account. <br>
                            <!--We are completely transparent, and you can track all deposits on our site <a href="https://blockchain.info/address/">here</a>--></small>
                    </div>
                    <form action="{{ route('deposit_post') }}" method="post" accept-charset="utf-8">
                        {{ csrf_field() }}
                        <div class="col-md-4 col-md-offset-4">
                            <button name="check_deposit" type="submit" class="btn btn-primary btn-block">Confirm Deposit</button>
                        </div>
                    </form>
                </div>
            </div>
        </section>
    </div>
@endsection

resources/views/front/privpol.blade.php
@extends('layouts.template')


@section('content')
    <div class="content-wrapper">
        <section class="content-header">
            <h1>
                PRIVACY POLICY
                <small>READ OUR PRIVACY POLICY</small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="{{ route('home') }}"><i class="fa fa-dashboard"></i> Home</a></li>
                <li class="active">privacy policy</li>
            </ol>
        </section>

        <section class="content">
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">Our privacy policy</h3>
                </div>
                <div class="box-body">
                    <div class="col-md-offset-2 col-md-8">
                    <p>
                        You agree that all information, communications, materials coming from Btcroyals
                        are unsolicited and must be kept private, confidential and protected from any
                        disclosure. Moreover, the information, communications, and materials contained
                        herein are not to be regarded as an offer, or a solicitation for investments in
                        any jurisdiction which deems non-public offers or solicitations unlawful, nor to
                        any person to whom it will be unlawful to make such offer or solicitation.
                    </p>
                        <p>
                        Like most commercial website owners, we may also use what is known as "cookie"
                        technology. A "cookie" is an element of data that a website can send to your browser
                        when you link to that website. It is not a computer program and has no ability to
                        read data residing on your computer or instruct it to perform any step or function.
                        By assigning a unique data element to each visitor, the website is able to recognize
                        repeat users, track usage patterns and better serve you when you return to that site.
                        For example, a cookie can be used to store your preferences for certain kinds of
                        information or to store a password so that you do not have to input it every time you
                        visit our Site. The cookie does not extract other personal information about you,
                        such as your name and address. Most browsers provide a simple procedure that will
                        enable you to control whether you want to receive cookies by notifying you when a
                        website is about to deposit a cookie file.
                        </p>
                        <p>
                        All the data giving by a member to
                        Cryptoflare will be only privately used and not disclosed to any third parties.
                        Cryptoflare is not responsible or liable for any loss of data.
                        </p>

                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection

resources/views/front/setting.blade.php
@extends('layouts.template')

@section('content')
    <div class="content-wrapper">
        <section class="content-header">
            <h1>
                SETTINGS
                <small>CHANGE YOUR PROFILE SETTINGS</small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="{{ route('home') }}"><i class="fa fa-dashboard"></i> Home</a></li>
                <li class="active">Setting</li>
            </ol>
        </section>
        @include('partials.errorbag')
        @if(session()->has('info'))
            @include('partials.error',['type'=>session('info')['type'],'message'=> session('info')['message']])
        @endif
        <section class="content">
            <div class="box">
                <div class="box-header with-border">
                </div>
                <div class="box-body">

                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                <div class="col-md-4">
                    <div class="box box-primary">
                        <div class="box-body box-profile">
                            <h3 class="profile-username text-center">{{ucfirst(auth()->user()->name)}}</h3>
                            <ul class="list-group list-group-unbordered">

                                <li class="list-group-item">
                                    <b>Email</b> <a class="pull-right">{{auth()->user()->email}}</a>
                                </li><li class="list-group-item">
                                    <b>Uplink</b> <a class="pull-right alert-warning">{{auth()->user()->parent}}</a>
                                </li>
                                <li class="list-group-item">
                                    <b>BTC address to send Deposit</b>
                                    <input class="form-control" id="btc" value="{{auth()->user()->bit_deposit_address}}" type="text" readonly/>
                                </li>
                                <li class="list-group-item">
                                    <b>BTC address for withdraw payment</b>
                                    <input class="form-control" value="{{auth()->user()->bit_owner_address}}" type="text" readonly />
                                </li>
                            </ul>
                        </div>
                        <!-- /.box-body -->
                    </div>
                </div>
                    <div class="col-md-8">
                        <div class="box box-info">
                            <!-- /.box-header -->
                            <div class="box box-primary">
                                <div class="box-header with-border">
                                    <h3 class="box-title"></h3>
                                </div>
                                <!-- /.box-header -->
                                <!-- form start -->
                                <form role="form" method="post" action="{{route('setting.store')}}">
                                    {{ csrf_field() }}
                                    <div class="box-body">
                                        <div class="form-group">
                                            <label for="exampleInputPassword1">BTC address to send deposit</label>
                                            <input class="form-control" value="{{ auth()->user()->bit_deposit_address }}" id="btc" placeholder="" type="text" readonly/>
                                        </div>

                                        <div class="form-group">
                                            <label for="exampleInputEmail1">Recipient BTC address for payouts</label>
                                            <input class="form-control" name="btc_address" id="btc_address" value="{{auth()->user()->bit_owner_address}}" placeholder="BTC address" type="text">
                                            <small>You may leave this empty and enter it whenever you want to perform withdraw transaction</small>
                                        </div>
                                        @if(!is_null(auth()->user()->facebook_id) && is_null(auth()->user()->password))
                                        <blockquote class="text-red">You can create a password to enable you login later with the local login system</blockquote>
                                        @endif
                                        <div class="form-group">
                                            <label for="password">New Password</label>
                                            <input class="form-control" name="password" id="password" placeholder="Password" type="password">
                                        </div>
                                        <div class="form-group">
                                            <label for="confirm_password">Re-enter New Password</label>
                                            <input class="form-control" name="password_confirmation" placeholder="Password" type="password">
                                        </div>
                                    </div>
                                    <!-- /.box-body -->

                                    <div class="box-footer">
                                        <button type="submit" class="btn btn-primary btn-block">Save Settings</button>
                                    </div>
                                </form>
                            </div>

                        </div>
                    </div>
                </div>
                <!-- /.box-footer-->
            </div>
        </section>
    </div>
@endsection